from church_encodings.bool import b_true, b_false, b_and, b_not
from church_encodings.pair import p_pair, p_first, p_second

i_zero = ...
i_succ = lambda n: lambda x: f(n(f)(x))


i_one   = i_succ(i_zero)
i_two   = i_succ(i_one)
i_three = i_succ(i_two)
i_four  = i_succ(i_three)
i_five  = i_succ(i_four)
i_six   = i_succ(i_five)
i_seven = i_succ(i_six)
i_eight = i_succ(i_seven)
i_nine  = i_succ(i_eight)
i_ten   = i_succ(i_nine)

_phi = ...
i_pred = ...

i_add = ...
i_sub = ...
i_mul = ...

i_is_zero = ...
i_leq = ...
i_lt = ...
i_eq = ...

i_div = ...
i_mod = ...